#!/bin/sh 

rm -rf public

mkdir public
cp -R images public/images

for f in pages/*.md
do
    echo "Processing $f file..."
    base=$(basename $f .md)
    echo "As $base file..."

    cat layout/header.html > public/$base.html
    markdown layout/page-head.md >> public/$base.html

    markdown $f >> public/$base.html

    cat layout/footer.html >> public/$base.html
done
